USE [C:\USERS\JP_51\DESKTOP\STARDEWVALLEY\STARDEWVALLEY\STARDEWVALLEY.MDF]

EXECUTE sp_helpindex Habitantes


CREATE TABLE HAB_ITEM 
(
	ID_Habitante SMALLINT NOT NULL ,
	ID_Item SMALLINT NOT NULL,
	Agrada BIT,
	CONSTRAINT Clave_Hab_Item PRIMARY KEY CLUSTERED 
	(
		ID_Habitante,
		ID_Item
	)

);

DROP TABLE HAB_ITEM

--CREATE CLUSTERED INDEX Indice_Habitante_Item ON HAB_ITEM (ID_Habitante ASC, ID_Item ASC)

ALTER TABLE HAB_ITEM ADD CONSTRAINT FK_Habitante FOREIGN KEY (ID_Habitante) REFERENCES HABITANTES (ID_Habitante);

ALTER TABLE HAB_ITEM ADD CONSTRAINT FK_Item FOREIGN KEY (ID_Item) REFERENCES Item (ID_Item);

ALTER TABLE HAB_ITEM DROP CONSTRAINT FK_Habitante;

--SHOW create table HAB_ITEM, 